name: Chess

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  chess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Chess
        uses: marcizhu/readme-chess@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
